// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOR52jKlKY94Mb_ILLGckCKiWbkssZ1r8',
    appId: '1:604257048628:web:1049dbb2b2b7ed93161261',
    messagingSenderId: '604257048628',
    projectId: 'instagram-1368e',
    authDomain: 'instagram-1368e.firebaseapp.com',
    storageBucket: 'instagram-1368e.appspot.com',
    measurementId: 'G-EV1TRKK4J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3H6HbyaHrpqTY3UFINkz9p9USx__udTQ',
    appId: '1:604257048628:android:0c700be6a57b6004161261',
    messagingSenderId: '604257048628',
    projectId: 'instagram-1368e',
    storageBucket: 'instagram-1368e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ3V8E9IY8rHBe5dtG6DajL64zOdgSt-Q',
    appId: '1:604257048628:ios:b97536121ce55367161261',
    messagingSenderId: '604257048628',
    projectId: 'instagram-1368e',
    storageBucket: 'instagram-1368e.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ3V8E9IY8rHBe5dtG6DajL64zOdgSt-Q',
    appId: '1:604257048628:ios:b97536121ce55367161261',
    messagingSenderId: '604257048628',
    projectId: 'instagram-1368e',
    storageBucket: 'instagram-1368e.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOR52jKlKY94Mb_ILLGckCKiWbkssZ1r8',
    appId: '1:604257048628:web:c03488c8289090f3161261',
    messagingSenderId: '604257048628',
    projectId: 'instagram-1368e',
    authDomain: 'instagram-1368e.firebaseapp.com',
    storageBucket: 'instagram-1368e.appspot.com',
    measurementId: 'G-81Q1PKP40M',
  );
}
